//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 28.09.2015 18:46:51
namespace balldbModel
{
    
    /// <summary>
    /// There are no comments for balldbEntities in the schema.
    /// </summary>
    public partial class balldbEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new balldbEntities object using the connection string found in the 'balldbEntities' section of the application configuration file.
        /// </summary>
        public balldbEntities() : 
                base("name=balldbEntities", "balldbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new balldbEntities object.
        /// </summary>
        public balldbEntities(string connectionString) : 
                base(connectionString, "balldbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new balldbEntities object.
        /// </summary>
        public balldbEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "balldbEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
